### ISSUE TITLE
Need help running examples

### ISSUE THREAD

**Issue by HussainAther** [vettorazi/react-three-8thwall#1]
I'm trying to run the examples given. 

Basically, I have this script `main.jsx` :
```
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'
ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
```

When I change it to:
```
import React from 'react';
import ReactDOM from 'react-dom/client';
import DreiRefraction from './examples';
// import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <DreiRefraction />
  </React.StrictMode>
);
```
I receive the error:
[RollupError: "default" is not exported by "src/examples.js", imported by "src/main.jsx".
](url)

**Comment by HussainAther** [comment]
I've tried renaming and rechanging the variables in both the `examples.js` and `main.jsx` scripts to see if the import/export works between the two files. The product still fails to deploy.

**Comment by vettorazi** [comment]
Hi @HussainAther,
The correct way is to work inside of `<App/>`, not in the main.js.
Import DreiRefraction in App and then add  ` <DreiRefraction /> `inside the `<Canvas><scene></scene></Canvas>`

Hope this helps.

**Comment by HussainAther** [comment]
OK, I've redownloaded the app and done as you said. Here's my code:

```
import XR8Scene from './XR8Scene';
import { useRef, useEffect } from 'react';
import './App.css';
import { Canvas } from '@react-three/fiber';
import DreiRefraction from './examples';

function App() {
  const canvasRef = useRef();
  const R3Scene = useRef();

  let { onxrloaded, cubeCamera } = XR8Scene(canvasRef, R3Scene);

  useEffect(() => {
    XRExtras.Loading.showLoading({ onxrloaded });
  }, []);

  return (
    <div className="App">
      <Canvas style={{ position: 'absolute' }}>
        <scene ref={R3Scene}>
          <ambientLight />
          <DreiRefraction />;
          <pointLight position={[10, 15, 10]} />
        </scene>
      </Canvas>
      <canvas
        ref={canvasRef}
        width="480"
        height="640"
        style={{ position: 'absolute' }}
      ></canvas>
    </div>
  );
}

export default App;
```


It still gives the error:

`RollupError: "default" is not exported by "src/examples.js", imported by "src/main.jsx".
`

**Comment by vettorazi** [comment]
Here's your problem:
`import DreiRefraction from './examples';`

try:
`import DreiRefraction from './DreiRefraction';`

**Comment by vettorazi** [comment]
./examples would be a folder, you need to import files. DreiRefraction.jsx is a file.

**Comment by vettorazi** [comment]
also,  this is jSX, not a JS file, so ` <DreiRefraction />;` like you did, with this semicolon won't work, delete that.

**Comment by HussainAther** [comment]
With those changes, it still gives the error: RollupError: "DreiRefraction" is not exported by "src/DreiRefraction.jsx", imported by "src/App.jsx".

**Comment by vettorazi** [comment]
Are you sure you are importing like this?
`import DreiRefraction from './DreiRefraction';` (with the ./ and without .jsx??)

**Comment by HussainAther** [comment]
I am, yes.

**Comment by vettorazi** [comment]
Can you share your code?

**Comment by HussainAther** [comment]
import XR8Scene from './XR8Scene';
import { useRef, useEffect } from 'react';
import './App.css';
import { Canvas } from '@react-three/fiber';
import DreiRefraction from './DreiRefraction';

function App() {
  const canvasRef = useRef();
  const R3Scene = useRef();

  let { onxrloaded, cubeCamera } = XR8Scene(canvasRef, R3Scene);

  useEffect(() => {
    XRExtras.Loading.showLoading({ onxrloaded });
  }, []);

  return (
    <div className="App">
      <Canvas style={{ position: 'absolute' }}>
        <scene ref={R3Scene}>
          <ambientLight />
          <DreiRefraction />
          <pointLight position={[10, 15, 10]} />
        </scene>
      </Canvas>
      <canvas
        ref={canvasRef}
        width="480"
        height="640"
        style={{ position: 'absolute' }}
      ></canvas>
    </div>
  );
}

export default App;

**Comment by vettorazi** [comment]
The code you provided is wrong. you deleted essential components from React.
Here's the fixed one.

```
import XR8Scene from './XR8Scene';
import { useRef, useEffect } from 'react';
import './App.css';
import { Canvas } from '@react-three/fiber';
import DreiRefraction from './DreiRefraction';

function App() {
  const canvasRef = useRef();
  const R3Scene = useRef();

  let { onxrloaded, cubeCamera } = XR8Scene(canvasRef, R3Scene);

  useEffect(() => {
    XRExtras.Loading.showLoading({ onxrloaded });
  }, []);

  return (
    <div className="App">
      <Canvas style={{ position: 'absolute' }}>
        <scene ref={R3Scene}>
          <ambientLight />
         <DreiRefraction/>
          <pointLight position={[10, 15, 10]} />
        </scene>
      </Canvas>
      <canvas
        ref={canvasRef}
        width="480"
        height="640"
        style={{ position: 'absolute' }}
      ></canvas>
    </div>
  );
}

export default App;
```

**Comment by vettorazi** [comment]
Note what I'm doing here:
It's exactly the same App.js file from this repo, but I imported the DreiRefraction example with:
import DreiRefraction from './DreiRefraction';

and I added this component in the middle of the canvas.

Hope it helps.

**Comment by HussainAther** [comment]
hi, thank you for the code, but it still gives the same error.

**Comment by vettorazi** [comment]
Oh, sorry about that. add the the props that are missing:
`<DreiRefraction envMap={cubeCamera.renderTarget.texture} />`

So your code will be like this.
```
import XR8Scene from './XR8Scene';
import { useRef, useEffect } from 'react';
import './App.css';
import { Canvas } from '@react-three/fiber';
import DreiRefraction from './DreiRefraction';

function App() {
  const canvasRef = useRef();
  const R3Scene = useRef();

  let { onxrloaded, cubeCamera } = XR8Scene(canvasRef, R3Scene);

  useEffect(() => {
    XRExtras.Loading.showLoading({ onxrloaded });
  }, []);

  return (
    <div className="App">
      <Canvas style={{ position: 'absolute' }}>
        <scene ref={R3Scene}>
          <ambientLight />
<DreiRefraction envMap={cubeCamera.renderTarget.texture} />
          <pointLight position={[10, 15, 10]} />
        </scene>
      </Canvas>
      <canvas
        ref={canvasRef}
        width="480"
        height="640"
        style={{ position: 'absolute' }}
      ></canvas>
    </div>
  );
}

export default App;

```

**Comment by HussainAther** [comment]
I've added that but it doens't fix the error.

**Comment by vettorazi** [comment]
can you be more descriptive? maybe sharing what is the error, and screenshots of what you are seeing?

**Comment by HussainAther** [comment]
OK, so I'm running the app through Vercel (https://vercel.com/) and receive this error:

Expand 34 Lines
--
20:11:34.854 | RollupError: "default" is not exported by "src/examples.js", imported by "src/App.jsx".
20:11:34.855 | at error (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:2130:30)
20:11:34.855 | at Module.error (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:13514:16)
20:11:34.855 | at Module.traceVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:13935:29)
20:11:34.855 | at ModuleScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:12480:39)
20:11:34.855 | at FunctionScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:7008:38)
20:11:34.855 | at ChildScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:7008:38)
20:11:34.855 | at Identifier.bind (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:8170:40)
20:11:34.855 | at CallExpression.bind (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:5772:28)
20:11:34.855 | at CallExpression.bind (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:9732:15)
20:11:34.855 | at ArrayExpression.bind (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:5772:28)
20:11:34.899 | error Command failed with exit code 1.
20:11:34.899 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
20:11:34.920 | Error: Command "yarn run build" exited with 1
20:11:35.311 | BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1

**Comment by HussainAther** [comment]
Here are a few screenshots: https://imgur.com/a/B3U6XfK

**Comment by HussainAther** [comment]
Neve rmind, looks like I got it to work when I run it using the QR code directly from the 8th Wall website. https://imgur.com/a/ikJNQ02
